# Cleaning Maryland Data  
Mary Glantz  
Data 205

In [1]:
import json
import numpy as np
import pandas as pd
import requests

In [2]:
mdcrashdf = pd.DataFrame(requests.get('https://opendata.maryland.gov/resource/65du-s3qu.json').json())
mdcrashdf.head()

,year,quarter,light_desc,light_code,county_desc,county_no,collision_type_desc,collision_type_code,fix_obj_desc,fix_obj_code,...,reference_road_name,muni_code,rte_no,route_type_code,logmile_dir_flag_desc,logmile_dir_flag,reference_no,reference_type_code,reference_suffix,rte_suffix
0,2020,Q2,Daylight,1,Baltimore,3,Other,88,Not Applicable,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020,Q2,NaN,6.02,Baltimore City,24,Other,88,Other Pole,10,...,NORTH AVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020,Q2,Daylight,1,Montgomery,15,Other,88,Not Applicable,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017,Q2,Daylight,1,Baltimore City,24,Single Vehicle,17,Not Applicable,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020,Q2,Daylight,1,Cecil,7,Same Direction Rear End,3,Not Applicable,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
mdcrashdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 56 columns):
year                           1000 non-null object
quarter                        1000 non-null object
light_desc                     949 non-null object
light_code                     1000 non-null object
county_desc                    1000 non-null object
county_no                      1000 non-null object
collision_type_desc            1000 non-null object
collision_type_code            1000 non-null object
fix_obj_desc                   915 non-null object
fix_obj_code                   1000 non-null object
report_no                      1000 non-null object
report_type                    999 non-null object
weather_desc                   260 non-null object
weather_code                   1000 non-null object
acc_date                       1000 non-null object
acc_time                       1000 non-null object
signal_flag_desc               1000 non-null object
signal_flag                    1000 non-null object
c_m_zone_flag                  1000 non-null object
agency_code                    1000 non-null object
area_code                      1000 non-null object
harm_event_desc1               977 non-null object
harm_event_code1               1000 non-null object
harm_event_desc2               1000 non-null object
harm_event_code2               1000 non-null object
latitude                       1000 non-null object
longitude                      1000 non-null object
geocoded_column                1000 non-null object
:@computed_region_r4de_cuuv    996 non-null object
junction_desc                  628 non-null object
junction_code                  666 non-null object
surf_cond_desc                 666 non-null object
surf_cond_code                 666 non-null object
lane_desc                      549 non-null object
lane_code                      549 non-null object
rd_cond_desc                   666 non-null object
rd_cond_code                   666 non-null object
rd_div_desc                    661 non-null object
rd_div_code                    666 non-null object
loc_code                       425 non-null object
log_mile                       666 non-null object
mainroad_name                  666 non-null object
distance                       666 non-null object
feet_miles_flag_desc           649 non-null object
feet_miles_flag                666 non-null object
distance_dir_flag              666 non-null object
reference_road_name            666 non-null object
muni_code                      590 non-null object
rte_no                         590 non-null object
route_type_code                590 non-null object
logmile_dir_flag_desc          590 non-null object
logmile_dir_flag               590 non-null object
reference_no                   590 non-null object
reference_type_code            590 non-null object
reference_suffix               18 non-null object
rte_suffix                     13 non-null object
dtypes: object(56)
memory usage: 437.6+ KB

In [4]:
mdcrashdf['year'] = pd.to_datetime(mdcrashdf['year'])
mdcrashdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 56 columns):
year                           1000 non-null datetime64[ns]
quarter                        1000 non-null object
light_desc                     949 non-null object
light_code                     1000 non-null object
county_desc                    1000 non-null object
county_no                      1000 non-null object
collision_type_desc            1000 non-null object
collision_type_code            1000 non-null object
fix_obj_desc                   915 non-null object
fix_obj_code                   1000 non-null object
report_no                      1000 non-null object
report_type                    999 non-null object
weather_desc                   260 non-null object
weather_code                   1000 non-null object
acc_date                       1000 non-null object
acc_time                       1000 non-null object
signal_flag_desc               1000 non-null object
signal_flag                    1000 non-null object
c_m_zone_flag                  1000 non-null object
agency_code                    1000 non-null object
area_code                      1000 non-null object
harm_event_desc1               977 non-null object
harm_event_code1               1000 non-null object
harm_event_desc2               1000 non-null object
harm_event_code2               1000 non-null object
latitude                       1000 non-null object
longitude                      1000 non-null object
geocoded_column                1000 non-null object
:@computed_region_r4de_cuuv    996 non-null object
junction_desc                  628 non-null object
junction_code                  666 non-null object
surf_cond_desc                 666 non-null object
surf_cond_code                 666 non-null object
lane_desc                      549 non-null object
lane_code                      549 non-null object
rd_cond_desc                   666 non-null object
rd_cond_code                   666 non-null object
rd_div_desc                    661 non-null object
rd_div_code                    666 non-null object
loc_code                       425 non-null object
log_mile                       666 non-null object
mainroad_name                  666 non-null object
distance                       666 non-null object
feet_miles_flag_desc           649 non-null object
feet_miles_flag                666 non-null object
distance_dir_flag              666 non-null object
reference_road_name            666 non-null object
muni_code                      590 non-null object
rte_no                         590 non-null object
route_type_code                590 non-null object
logmile_dir_flag_desc          590 non-null object
logmile_dir_flag               590 non-null object
reference_no                   590 non-null object
reference_type_code            590 non-null object
reference_suffix               18 non-null object
rte_suffix                     13 non-null object
dtypes: datetime64[ns](1), object(55)
memory usage: 437.6+ KB

In [7]:
county_desc = mdcrashdf.county_desc
county_desc_uniques = county_desc.unique()
county_desc_uniques

array(['Baltimore', 'Baltimore City', 'Montgomery', 'Cecil',
       'Anne Arundel', 'Frederick', "Prince George's", 'Talbot',
       'Harford', 'Kent', 'Wicomico', "Queen Anne's", 'Worcester',
       'Carroll', 'Howard', 'Charles', 'Garrett', 'Dorchester', 'Calvert',
       'Washington', "St. Mary's", 'Allegany', 'Somerset', 'Caroline'],
      dtype=object)

In [8]:
pgcrash = mdcrashdf.loc[mdcrashdf['county_desc']=='Prince George\'s' ]

In [9]:
pgcrash.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 161 entries, 12 to 990
Data columns (total 56 columns):
year                           161 non-null datetime64[ns]
quarter                        161 non-null object
light_desc                     157 non-null object
light_code                     161 non-null object
county_desc                    161 non-null object
county_no                      161 non-null object
collision_type_desc            161 non-null object
collision_type_code            161 non-null object
fix_obj_desc                   150 non-null object
fix_obj_code                   161 non-null object
report_no                      161 non-null object
report_type                    161 non-null object
weather_desc                   36 non-null object
weather_code                   161 non-null object
acc_date                       161 non-null object
acc_time                       161 non-null object
signal_flag_desc               161 non-null object
signal_flag                    161 non-null object
c_m_zone_flag                  161 non-null object
agency_code                    161 non-null object
area_code                      161 non-null object
harm_event_desc1               160 non-null object
harm_event_code1               161 non-null object
harm_event_desc2               161 non-null object
harm_event_code2               161 non-null object
latitude                       161 non-null object
longitude                      161 non-null object
geocoded_column                161 non-null object
:@computed_region_r4de_cuuv    161 non-null object
junction_desc                  96 non-null object
junction_code                  102 non-null object
surf_cond_desc                 102 non-null object
surf_cond_code                 102 non-null object
lane_desc                      86 non-null object
lane_code                      86 non-null object
rd_cond_desc                   102 non-null object
rd_cond_code                   102 non-null object
rd_div_desc                    102 non-null object
rd_div_code                    102 non-null object
loc_code                       30 non-null object
log_mile                       102 non-null object
mainroad_name                  102 non-null object
distance                       102 non-null object
feet_miles_flag_desc           101 non-null object
feet_miles_flag                102 non-null object
distance_dir_flag              102 non-null object
reference_road_name            102 non-null object
muni_code                      101 non-null object
rte_no                         101 non-null object
route_type_code                101 non-null object
logmile_dir_flag_desc          101 non-null object
logmile_dir_flag               101 non-null object
reference_no                   101 non-null object
reference_type_code            101 non-null object
reference_suffix               9 non-null object
rte_suffix                     1 non-null object
dtypes: datetime64[ns](1), object(55)
memory usage: 71.7+ KB

In [10]:
fredcrash = mdcrashdf.loc[mdcrashdf['county_desc']=='Frederick']
fredcrash.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21 entries, 6 to 992
Data columns (total 56 columns):
year                           21 non-null datetime64[ns]
quarter                        21 non-null object
light_desc                     18 non-null object
light_code                     21 non-null object
county_desc                    21 non-null object
county_no                      21 non-null object
collision_type_desc            21 non-null object
collision_type_code            21 non-null object
fix_obj_desc                   18 non-null object
fix_obj_code                   21 non-null object
report_no                      21 non-null object
report_type                    21 non-null object
weather_desc                   3 non-null object
weather_code                   21 non-null object
acc_date                       21 non-null object
acc_time                       21 non-null object
signal_flag_desc               21 non-null object
signal_flag                    21 non-null object
c_m_zone_flag                  21 non-null object
agency_code                    21 non-null object
area_code                      21 non-null object
harm_event_desc1               21 non-null object
harm_event_code1               21 non-null object
harm_event_desc2               21 non-null object
harm_event_code2               21 non-null object
latitude                       21 non-null object
longitude                      21 non-null object
geocoded_column                21 non-null object
:@computed_region_r4de_cuuv    21 non-null object
junction_desc                  18 non-null object
junction_code                  19 non-null object
surf_cond_desc                 19 non-null object
surf_cond_code                 19 non-null object
lane_desc                      10 non-null object
lane_code                      10 non-null object
rd_cond_desc                   19 non-null object
rd_cond_code                   19 non-null object
rd_div_desc                    19 non-null object
rd_div_code                    19 non-null object
loc_code                       2 non-null object
log_mile                       19 non-null object
mainroad_name                  19 non-null object
distance                       19 non-null object
feet_miles_flag_desc           19 non-null object
feet_miles_flag                19 non-null object
distance_dir_flag              19 non-null object
reference_road_name            19 non-null object
muni_code                      19 non-null object
rte_no                         19 non-null object
route_type_code                19 non-null object
logmile_dir_flag_desc          19 non-null object
logmile_dir_flag               19 non-null object
reference_no                   19 non-null object
reference_type_code            19 non-null object
reference_suffix               0 non-null object
rte_suffix                     0 non-null object
dtypes: datetime64[ns](1), object(55)
memory usage: 9.4+ KB

In [12]:
fredcrash.head()

,year,quarter,light_desc,light_code,county_desc,county_no,collision_type_desc,collision_type_code,fix_obj_desc,fix_obj_code,...,reference_road_name,muni_code,rte_no,route_type_code,logmile_dir_flag_desc,logmile_dir_flag,reference_no,reference_type_code,reference_suffix,rte_suffix
6,2020-01-01,Q2,Daylight,1,Frederick,10,Same Movement Angle,11,Not Applicable,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,2020-01-01,Q2,Daylight,1,Frederick,10,Single Vehicle,17,Tree Shrubbery,11,...,GAS HOUSE PIKE,0,415,CO,South,S,413,CO,NaN,NaN
204,2020-01-01,Q2,NaN,6.02,Frederick,10,Single Vehicle,17,NaN,22.03,...,SUNDAYS LA,0,178,CO,North,N,721,CO,NaN,NaN
225,2020-01-01,Q2,Daylight,1,Frederick,10,Head On Left Turn,2,Not Applicable,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
332,2020-01-01,Q2,Daylight,1,Frederick,10,Single Vehicle,17,Light Support Pole,8,...,COPPER OAKS DR,0,466,CO,North,N,15,MU,NaN,NaN

Note:  check how to add more api or data entries